import { ReactNode } from "react";

interface EndpointSnippetProps {
  endpoint?: string;
  selector?: string;
  children?: ReactNode;
}

interface SchemaSnippetProps {
  type?: string;
  title?: string;
  children?: ReactNode;
}

interface WebhookPayloadSnippetProps {
  webhook?: string;
  children?: ReactNode;
}

/**
 * Stub components for Fern API snippet references.
 * These originally pulled inline schema data from Fern's API definitions.
 * In Docusaurus, the full API reference is generated by the OpenAPI plugin.
 * These render a placeholder pointing to the API reference.
 */

export function EndpointRequestSnippet({ endpoint }: EndpointSnippetProps) {
  return (
    <div className="admonition admonition-info alert alert--info">
      <div className="admonition-content">
        <p>
          See the full request schema for <code>{endpoint}</code> in the{" "}
          <a href="/apis/calling/calling-api">REST API reference</a>.
        </p>
      </div>
    </div>
  );
}

export function EndpointResponseSnippet({ endpoint }: EndpointSnippetProps) {
  return (
    <div className="admonition admonition-info alert alert--info">
      <div className="admonition-content">
        <p>
          See the full response schema for <code>{endpoint}</code> in the{" "}
          <a href="/apis/calling/calling-api">REST API reference</a>.
        </p>
      </div>
    </div>
  );
}

export function EndpointSchemaSnippet({ endpoint, selector }: EndpointSnippetProps) {
  const label = selector === "request" ? "request" : "request/response";
  return (
    <div className="admonition admonition-info alert alert--info">
      <div className="admonition-content">
        <p>
          See the full {label} schema for <code>{endpoint}</code> in the{" "}
          <a href="/apis/calling/calling-api">REST API reference</a>.
        </p>
      </div>
    </div>
  );
}

export function SchemaSnippet({ type, title }: SchemaSnippetProps) {
  return (
    <div className="admonition admonition-info alert alert--info">
      <div className="admonition-content">
        <p>
          {title || `The ${type} object`}: see the{" "}
          <a href="/apis/calling/calling-api">REST API reference</a>{" "}
          for the full schema.
        </p>
      </div>
    </div>
  );
}

export function WebhookPayloadSnippet({ webhook }: WebhookPayloadSnippetProps) {
  return (
    <div className="admonition admonition-info alert alert--info">
      <div className="admonition-content">
        <p>
          See the full payload for <code>{webhook}</code> in the{" "}
          <a href="/apis/calling/calling-api">REST API reference</a>.
        </p>
      </div>
    </div>
  );
}
