import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const callFlowBuilderSidebar: SidebarsConfig = {
  callFlowBuilderSidebar: [
    {
      type: "category",
      label: "Core",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "call-flow-builder/core" }
      ],
    },
    {
      type: "category",
      label: "Nodes",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "call-flow-builder/nodes" }
      ],
    },
  ],
};

export default callFlowBuilderSidebar;
