import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const compatibilityApiSidebars: SidebarsConfig = {
  // cXML tab sidebar
  compatibilityApiReferenceSidebar: [
    {
      type: "category",
      label: "Core",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "compatibility-api/cxml/core",
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "compatibility-api/cxml/guides",
        },
      ],
    },
    {
      type: "category",
      label: "Voice",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "compatibility-api/cxml/voice",
        },
      ],
    },
    {
      type: "category",
      label: "Messaging",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "compatibility-api/cxml/messaging",
        },
      ],
    },
    {
      type: "category",
      label: "Fax",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "compatibility-api/cxml/fax",
        },
      ],
    },
  ],

  // SDKs tab sidebar
  compatibilityApiClientLibrariesSidebar: [
    {
      type: "category",
      label: "Core",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "compatibility-api/sdks/core",
        },
      ],
    },
    {
      type: "category",
      label: "REST Client Methods",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "compatibility-api/sdks/methods",
        },
      ],
    },
  ],

  // REST API tab sidebar
  apiCompatibilitySidebar: [
    {
      type: "category",
      label: "Core",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "compatibility-api/rest-api/core",
        },
      ],
    },
    {
      type: "category",
      label: "REST Endpoints",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/compatibility-api/rest/sidebar"),
    },
  ],
};

export default compatibilityApiSidebars;
