import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const platformSidebars: SidebarsConfig = {
  platformPlatform: [
    {
      type: "doc",
      id: "platform/getting-started",
      label: "Get started",
    },
    {
      type: "category",
      label: "Setup",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/platform/setup" }
      ],
    },
    {
      type: "category",
      label: "Core",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/platform/core" }
      ],
    },
    {
      type: "category",
      label: "Architecture",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/platform/call-fabric" }
      ],
    },
    {
      type: "category",
      label: "Phone numbers",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/platform/phone-numbers" }
      ],
    },
    {
      type: "category",
      label: "Integrations",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/platform/integrations" }
      ],
    },
  ],

  platformCalling: [
    {
      type: "doc",
      id: "platform/calling/index",
      label: "Overview",
    },
    {
      type: "category",
      label: "Voice",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/calling/voice" }
      ],
    },
    {
      type: "category",
      label: "Video",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/calling/video" }
      ],
    },
    {
      type: "category",
      label: "Fax",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/calling/fax" }
      ],
    },
  ],

  platformAi: [
    {
      type: "doc",
      id: "platform/ai/overview",
      label: "Overview",
    },
    {
      type: "category",
      label: "Get started",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/ai/get-started" }
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/ai/guides" }
      ],
    },
  ],

  platformMessaging: [
    {
      type: "category",
      label: "SMS & MMS",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/messaging/sms" }
      ],
    },
    {
      type: "category",
      label: "Chat",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/messaging/chat" }
      ],
    },
  ],

  platformTools: [
    {
      type: "category",
      label: "Tools",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "platform/tools" }
      ],
    },
  ],

};

export default platformSidebars;
