/*
* REST API endpoint sidebars are autogenerated by `docusaurus-plugin-openapi-docs`.
* Generated sidebars are created in each API's outputDir (e.g. docs/main/apis/calling/).
*
* URL structure matches Fern:
*   SignalWire APIs: /apis/<api-name>/<endpoint>
*   Compatibility API: /compatibility-api/rest/<endpoint>
*/

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const restApiSidebars: SidebarsConfig = {
  apiSidebar: [
    {
      type: "category",
      label: "Core",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "apis/core",
        },
      ],
    },
    {
      type: "category",
      label: "Calling",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/apis/calling/sidebar"),
    },
    {
      type: "category",
      label: "Voice",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/apis/voice/sidebar"),
    },
    {
      type: "category",
      label: "Messaging",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/apis/messaging/sidebar"),
    },
    {
      type: "category",
      label: "Fax",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/apis/fax/sidebar"),
    },
    {
      type: "category",
      label: "Chat",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/apis/chat/sidebar"),
    },
    {
      type: "category",
      label: "Video",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/apis/video/sidebar"),
    },
    {
      type: "category",
      label: "Fabric",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/apis/fabric/sidebar"),
    },
    {
      type: "category",
      label: "RELAY REST",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/apis/relay-rest/sidebar"),
    },
    {
      type: "category",
      label: "Project",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/apis/project/sidebar"),
    },
    {
      type: "category",
      label: "Datasphere",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/apis/datasphere/sidebar"),
    },
    {
      type: "category",
      label: "PubSub",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/apis/pubsub/sidebar"),
    },
    {
      type: "category",
      label: "Logs",
      collapsible: false,
      className: "menu-category",
      items: require("../../../docs/main/apis/logs/sidebar"),
    },
  ],
};

export default restApiSidebars;
