import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const swmlSidebars: SidebarsConfig = {
  swmlReferenceSidebar: [
    {
      type: "category",
      label: "Core",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "swml/get-started",
        },
        {
          type: "doc",
          id: "swml/reference/expressions",
        },
        {
          type: "doc",
          id: "swml/reference/template-functions",
        },
        {
          type: "doc",
          id: "swml/reference/variables",
        },
        {
          type: "doc",
          id: "swml/reference/schema",
        },
      ],
    },
    {
      type: "category",
      label: "Methods",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "swml/reference/methods",
        },
      ],
    },
  ],

  swmlGuidesSidebar: [
    {
      type: "category",
      label: "Quickstart",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "swml/guides/get-started",
        },
      ],
    },
    {
      type: "category",
      label: "Basics",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "swml/guides/basics",
        },
      ],
    },
    {
      type: "category",
      label: "Recipes",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "swml/guides/recipes",
        },
      ],
    },
    {
      type: "category",
      label: "SWAIG Functions",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "swml/guides/swaig",
        },
      ],
    },
  ],
};

export default swmlSidebars;
