user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    map_hash_max_size 4096;
    map_hash_bucket_size 256;

    map $uri $new_uri {
        include /etc/nginx/redirects.map;
    }

    map $args $args_suffix {
        default   "?$args";
        ""        "";
    }

    server {
        listen       80;
        server_name  localhost;

        if ($new_uri) {
            return 301 $new_uri$args_suffix;
        }
    }
}
