import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const signalwireSdkSidebar: SidebarsConfig = {
  signalwireSdkSidebar: [
    {
      type: "category",
      label: "SignalWire Client SDK",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "doc",
          label: "Overview",
          id: "index",
        },
        {
          type: "doc",
          label: "Call Fabric Architecture",
          id: "about_call_fabric",
        },
      ],
    },
    {
      type: "category",
      label: "Technical Reference",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "tech-ref",
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "guides",
        },
      ],
    },
  ],
};

export default signalwireSdkSidebar;
