import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const realtimeSdkSidebars: SidebarsConfig = {
  realtimeSdkReferenceSidebar: [
    {
      type: "category",
      label: "Core",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "tech-ref/core" }
      ],
    },
    {
      type: "category",
      label: "Voice",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "tech-ref/voice" }
      ],
    },
    {
      type: "category",
      label: "Video",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "tech-ref/video" }
      ],
    },
    {
      type: "category",
      label: "Messaging",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "tech-ref/messaging" }
      ],
    },
    {
      type: "category",
      label: "PubSub",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "tech-ref/pubsub" }
      ],
    },
    {
      type: "category",
      label: "Chat",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "tech-ref/chat" }
      ],
    },
    {
      type: "category",
      label: "Task",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "tech-ref/task" }
      ],
    },
  ],

  realtimeSdkGuidesSidebar: [
    {
      type: "category",
      label: "Core",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "guides/core" }
      ],
    },
    {
      type: "category",
      label: "Voice",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "guides/voice" }
      ],
    },
    {
      type: "category",
      label: "Messaging",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "guides/messaging" }
      ],
    },
  ],

};

export default realtimeSdkSidebars;
