import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const realtimeSdkV2Sidebars: SidebarsConfig = {
  realtimeSdkV2ReferenceNodeJs: [
    {
      type: "category",
      label: "Core",
      collapsible: true,
      items: [
        {
          type: "doc",
          id: "v2/language/nodejs",
          label: "Overview",
        },
        {
          type: "doc",
          id: "v2/language/nodejs/consumer",
          label: "Consumer",
        },
        {
          type: "doc",
          id: "v2/language/nodejs/relay-client",
          label: "Relay Client",
        },
        {
          type: "doc",
          id: "v2/language/nodejs/event",
          label: "Event",
        },
        {
          type: "doc",
          id: "v2/language/nodejs/examples",
          label: "Examples",
        }
      ],
    },
    {
      type: "category",
      label: "Calling",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/nodejs/calling" }
      ],
    },
    {
      type: "category",
      label: "Messaging",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/nodejs/messaging" }
      ],
    },
    {
      type: "category",
      label: "Task",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/nodejs/task" }
      ],
    },
  ],

  realtimeSdkV2ReferencePython: [
    {
      type: "category",
      label: "Core",
      collapsible: true,
      items: [
        {
          type: "doc",
          id: "v2/language/python",
          label: "Overview",
        },
        {
          type: "doc",
          id: "v2/language/python/consumer",
          label: "Consumer",
        },
        {
          type: "doc",
          id: "v2/language/python/relay-client",
          label: "Relay Client",
        },
        {
          type: "doc",
          id: "v2/language/python/event",
          label: "Event",
        },
        {
          type: "doc",
          id: "v2/language/python/examples",
          label: "Examples",
        }
      ],
    },
    {
      type: "category",
      label: "Calling",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/python/calling" }
      ],
    },
    {
      type: "category",
      label: "Messaging",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/python/messaging" }
      ],
    },
    {
      type: "category",
      label: "Task",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/python/task" }
      ],
    },
  ],

  realtimeSdkV2ReferenceRuby: [
    {
      type: "category",
      label: "Core",
      collapsible: true,
      items: [
        {
          type: "doc",
          id: "v2/language/ruby",
          label: "Overview",
        },
        {
          type: "doc",
          id: "v2/language/ruby/consumer",
          label: "Consumer",
        },
        {
          type: "doc",
          id: "v2/language/ruby/relay-client",
          label: "Relay Client",
        },
        {
          type: "doc",
          id: "v2/language/ruby/event",
          label: "Event",
        }
      ],
    },
    {
      type: "category",
      label: "Calling",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/ruby/calling" }
      ],
    },
    {
      type: "category",
      label: "Messaging",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/ruby/messaging" }
      ],
    },
    {
      type: "category",
      label: "Task",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/ruby/task" }
      ],
    },
  ],

  realtimeSdkV2ReferencePHP: [
    {
      type: "category",
      label: "Core",
      collapsible: true,
      items: [
        {
          type: "doc",
          id: "v2/language/php",
          label: "Overview",
        },
        {
          type: "doc",
          id: "v2/language/php/consumer",
          label: "Consumer",
        },
        {
          type: "doc",
          id: "v2/language/php/relay-client",
          label: "Relay Client",
        },
        {
          type: "doc",
          id: "v2/language/php/event",
          label: "Event",
        },
        {
          type: "doc",
          id: "v2/language/php/examples",
          label: "Examples",
        }
      ],
    },
    {
      type: "category",
      label: "Calling",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/php/calling" }
      ],
    },
    {
      type: "category",
      label: "Messaging",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/php/messaging" }
      ],
    },
    {
      type: "category",
      label: "Task",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/php/task" }
      ],
    },
  ],

  realtimeSdkV2ReferenceGo: [
    {
      type: "category",
      label: "Core",
      collapsible: true,
      items: [
        {
          type: "doc",
          id: "v2/language/golang",
          label: "Overview",
        },
        {
          type: "doc",
          id: "v2/language/golang/consumer",
          label: "Consumer",
        },
        {
          type: "doc",
          id: "v2/language/golang/relay-client",
          label: "Relay Client",
        },
        {
          type: "doc",
          id: "v2/language/golang/event",
          label: "Event",
        }
      ],
    },
    {
      type: "category",
      label: "Calling",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/golang/calling" }
      ],
    },
    {
      type: "category",
      label: "Messaging",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/golang/messaging" }
      ],
    },
    {
      type: "category",
      label: "Task",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/golang/task" }
      ],
    },
  ],

  realtimeSdkV2ReferenceNET: [
    {
      type: "category",
      label: "Core",
      collapsible: true,
      items: [
        {
          type: "doc",
          id: "v2/language/dotnet",
          label: "Overview",
        },
        {
          type: "doc",
          id: "v2/language/dotnet/consumer",
          label: "Consumer",
        },
        {
          type: "doc",
          id: "v2/language/dotnet/relay-client",
          label: "Relay Client",
        },
        {
          type: "doc",
          id: "v2/language/dotnet/event",
          label: "Event",
        },
        {
          type: "doc",
          id: "v2/language/dotnet/examples",
          label: "Examples",
        }
      ],
    },
    {
      type: "category",
      label: "Calling",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/dotnet/calling" }
      ],
    },
    {
      type: "category",
      label: "Messaging",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/dotnet/messaging" }
      ],
    },
    {
      type: "category",
      label: "Task",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/language/dotnet/task" }
      ],
    },
  ],

};

export default realtimeSdkV2Sidebars;
