import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const realtimeSdkV3Sidebars: SidebarsConfig = {
  realtimeSdkV3Reference: [
    {
      type: "category",
      label: "Core",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v3/tech-ref/core" }
      ],
    },
    {
      type: "category",
      label: "Voice",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v3/tech-ref/voice" }
      ],
    },
    {
      type: "category",
      label: "Video",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v3/tech-ref/video" }
      ],
    },
    {
      type: "category",
      label: "PubSub",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v3/tech-ref/pubsub" }
      ],
    },
    {
      type: "category",
      label: "Chat",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v3/tech-ref/chat" }
      ],
    },
    {
      type: "category",
      label: "Task",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v3/tech-ref/task" }
      ],
    },
    {
      type: "category",
      label: "Realtime Client",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v3/tech-ref/realtime-client" }
      ],
    },
  ],

};

export default realtimeSdkV3Sidebars;
