import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const agentsSdkSidebars: SidebarsConfig = {
  // Guides tab - matches Fern "Guides" tab
  agentsSdkGuidesSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "getting-started" },
      ],
    },
    {
      type: "category",
      label: "Core Concepts",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "core-concepts" },
      ],
    },
    {
      type: "category",
      label: "Building Agents",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "building-agents" },
      ],
    },
    {
      type: "category",
      label: "SWAIG Functions",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "swaig-functions" },
      ],
    },
    {
      type: "category",
      label: "Skills",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "skills" },
      ],
    },
    {
      type: "category",
      label: "Prefab Agents",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "prefabs" },
      ],
    },
    {
      type: "category",
      label: "Deployment",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "deployment" },
      ],
    },
    {
      type: "category",
      label: "Advanced Topics",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "advanced" },
      ],
    },
    {
      type: "category",
      label: "SignalWire Integration",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "signalwire-integration" },
      ],
    },
    {
      type: "category",
      label: "Examples",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "examples" },
      ],
    },
  ],

  // Reference tab - matches Fern "Reference" tab
  agentsSdkReferenceSidebar: [
    {
      type: "category",
      label: "API Reference",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "reference" },
      ],
    },
    {
      type: "category",
      label: "Appendix",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "appendix" },
      ],
    },
  ],
};

export default agentsSdkSidebars;
