import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const browserSdkSidebars: SidebarsConfig = {
  browserSdkReferenceSidebar: [
    {
      type: "category",
      label: "Core",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "reference/core" }
      ],
    },
    {
      type: "category",
      label: "SignalWire Client",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "reference/signalwire-client" }
      ],
    },
    {
      type: "category",
      label: "Video",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "reference/video" }
      ],
    },
    {
      type: "category",
      label: "Chat",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "reference/chat" }
      ],
    },
    {
      type: "category",
      label: "PubSub",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "reference/pubsub" }
      ],
    },
    {
      type: "category",
      label: "WebRTC",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "reference/webrtc" }
      ],
    },
  ],

  browserSdkGuidesSidebar: [
    {
      type: "category",
      label: "Core",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "guides/core" }
      ],
    },
    {
      type: "category",
      label: "Video",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "guides/video" }
      ],
    },
    {
      type: "category",
      label: "Chat",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "guides/chat" }
      ],
    },
  ],

  browserSdkClickToCallSidebar: [
    {
      type: "category",
      label: "Click-to-Call",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "click-to-call" }
      ],
    },
  ],

};

export default browserSdkSidebars;
