import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const browserSdkV2Sidebars: SidebarsConfig = {
  browserSdkV2Reference: [
    {
      type: "category",
      label: "Core",
      collapsible: true,
      items: [
        { type: "autogenerated", dirName: "v2/reference" }
      ],
    },
  ],

};

export default browserSdkV2Sidebars;
