# Calling API - outputs to specs/calling
extends: ../../tspconfig.yaml
emit:
  - "@typespec/openapi3"

options:
  "@typespec/openapi3":
    emitter-output-dir: "{cwd}/../../../specs/calling"
    output-file: openapi.yaml
    openapi-versions:
      - "3.1.0"
